package project;

import java.awt.ComponentOrientation;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author moizs
 */
public class mainScreen extends javax.swing.JFrame {

    /**
     * Creates new form mainScreen
     */
    public static surahScreen s;
    public static Quran q;
    public static topicScreen t;
    public static boolean S;
    public static boolean T;

    public mainScreen() throws UnsupportedEncodingException, IOException {
        q = new Quran();
        s = new surahScreen();
        t = new topicScreen();
        S = false;
        T = false;
        t.setVisible(false);
        s.setVisible(false);
        FileInputStream fstream = new FileInputStream("D://Project//surah names.txt");
        DataInputStream in = new DataInputStream(fstream);
        BufferedReader br = new BufferedReader(new InputStreamReader(in));
        String strLine;
        initComponents();
        topicCBox.setMaximumRowCount(8);

        ActionListener cbActionListener = new ActionListener() {//add actionlistner to listen for change
            @Override
            public void actionPerformed(ActionEvent e) {
                int index = surahAyahCBox.getSelectedIndex();
                int noOfAyah = q.noOfAyah(index);
                ayahCBox.removeAllItems();
                for (int i = 0; i < noOfAyah; i++) {
                    int temp = i + 1;
                    ayahCBox.addItem(Integer.toString(temp));
                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
        surahAyahCBox.addActionListener(cbActionListener);

        //Loading data//
        String[] names = new String[114];
        while ((strLine = br.readLine()) != null) {
            surahCBox.addItem(strLine.replaceFirst("    ", ""));
            surahAyahCBox.addItem(strLine.replaceFirst("    ", ""));
        }

        for (int i = 0; i < q.topics.Table.length; i++) {
            if (q.topics.Table[i] != null) {
                topicCBox.addItem(q.topics.Table[i].name);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainScreen = new javax.swing.JPanel();
        topicTxt = new javax.swing.JLabel();
        topicCBox = new javax.swing.JComboBox<>();
        topicGo = new javax.swing.JButton();
        surahTxt = new javax.swing.JLabel();
        surahCBox = new javax.swing.JComboBox<>();
        searchSurah = new javax.swing.JButton();
        surahAyatTxt = new javax.swing.JLabel();
        ayatTxt = new javax.swing.JLabel();
        surahAyahCBox = new javax.swing.JComboBox<>();
        ayahCBox = new javax.swing.JComboBox<>();
        searchAyah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quran Explorer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        mainScreen.setToolTipText("");

        topicTxt.setText("Topic");

        topicCBox.setMaximumRowCount(400);
        topicCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicCBoxActionPerformed(evt);
            }
        });

        topicGo.setText("Search");
        topicGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicGoActionPerformed(evt);
            }
        });

        surahTxt.setText("Surah");

        surahCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surahCBoxActionPerformed(evt);
            }
        });

        searchSurah.setText("Search");
        searchSurah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSurahActionPerformed(evt);
            }
        });

        surahAyatTxt.setText("Surah");

        ayatTxt.setText("Ayah");

        searchAyah.setText("Search");
        searchAyah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAyahActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quran Explorer");

        javax.swing.GroupLayout mainScreenLayout = new javax.swing.GroupLayout(mainScreen);
        mainScreen.setLayout(mainScreenLayout);
        mainScreenLayout.setHorizontalGroup(
            mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainScreenLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainScreenLayout.createSequentialGroup()
                        .addGroup(mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainScreenLayout.createSequentialGroup()
                                .addComponent(surahAyatTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(surahAyahCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ayatTxt)
                                .addGap(18, 18, 18)
                                .addComponent(ayahCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainScreenLayout.createSequentialGroup()
                                .addGroup(mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(topicTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(surahTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(surahCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(topicCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topicGo)
                            .addComponent(searchSurah)
                            .addComponent(searchAyah)))))
        );
        mainScreenLayout.setVerticalGroup(
            mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainScreenLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainScreenLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(topicCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(topicTxt)
                        .addComponent(topicGo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surahTxt)
                    .addComponent(surahCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchSurah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surahAyatTxt)
                    .addComponent(surahAyahCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ayatTxt)
                    .addComponent(ayahCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAyah))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void surahCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surahCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surahCBoxActionPerformed

    private void topicCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicCBoxActionPerformed

    }//GEN-LAST:event_topicCBoxActionPerformed

    private void searchSurahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSurahActionPerformed
        S = true;
        int index = surahCBox.getSelectedIndex();
        String display = q.getSurah(index + 1);
        s.display.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s.display.setText(display);
        s.display.setCaretPosition(0);
        s.setVisible(true);
    }//GEN-LAST:event_searchSurahActionPerformed

    private void searchAyahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAyahActionPerformed
        S = false;
        int indexSurah = surahAyahCBox.getSelectedIndex();
        int indexAyah = ayahCBox.getSelectedIndex();
        String display = q.getAyah(indexSurah + 1, indexAyah + 1);
        s.display.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s.display.setText(display);
        s.setVisible(true);
    }//GEN-LAST:event_searchAyahActionPerformed

    private void topicGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicGoActionPerformed
        T = true;
        String topic = (String) topicCBox.getSelectedItem();
        topic Topic = q.getTopic(topic);
        t.subTopicCBox.removeAllItems();
        t.topicDisplay.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        if (Topic.ayatExist()) {
            String result = q.searchTopic(topic);
            t.topicDisplay.setText(result);
            t.topicDisplay.setCaretPosition(0);
            if (Topic.subTopicExist()) {
                for (int i = 0; i < Topic.subTopic.length; i++) {
                    if (Topic.subTopic[i] != null) {
                        t.subTopicCBox.addItem(Topic.subTopic[i].name);
                    }
                }
            }
        } else {
            for (int i = 0; i < Topic.subTopic.length; i++) {
                if (Topic.subTopic[i] != null) {
                    t.subTopicCBox.addItem(Topic.subTopic[i].name);
                }
            }
            t.topicDisplay.setText("PLEASE SELECT A SUBTOPIC");
        }
        t.setVisible(true);
    }//GEN-LAST:event_topicGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new mainScreen().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
                /*try {
                   FileInputStream fstream = new FileInputStream("D://Project//surah names.txt");
                    DataInputStream in = new DataInputStream(fstream);
                    BufferedReader br = new BufferedReader(new InputStreamReader(in));
                    String strLine;
                    topicCBox.setMaximumRowCount(8);

                    ActionListener cbActionListener = new ActionListener() {//add actionlistner to listen for change
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            int index = surahAyahCBox.getSelectedIndex();
                            int noOfAyah = q.noOfAyah(index);
                            ayahCBox.removeAllItems();
                            for (int i = 0; i < noOfAyah; i++) {
                                int temp = i + 1;
                                ayahCBox.addItem(Integer.toString(temp));
                            }
                            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    };
                    surahAyahCBox.addActionListener(cbActionListener);

                    //Loading data//
                    String[] names = new String[114];
                    while ((strLine = br.readLine()) != null) {
                        surahCBox.addItem(strLine.replaceFirst("    ", ""));
                        surahAyahCBox.addItem(strLine.replaceFirst("    ", ""));
                    }

                    for (int i = 0; i < q.topics.Table.length; i++) {
                        if (q.topics.Table[i] != null) {
                            topicCBox.addItem(q.topics.Table[i].name);
                        }
                    }

                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
                }*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> ayahCBox;
    public javax.swing.JLabel ayatTxt;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel mainScreen;
    public javax.swing.JButton searchAyah;
    public javax.swing.JButton searchSurah;
    public static javax.swing.JComboBox<String> surahAyahCBox;
    public javax.swing.JLabel surahAyatTxt;
    public static javax.swing.JComboBox<String> surahCBox;
    public javax.swing.JLabel surahTxt;
    public static javax.swing.JComboBox<String> topicCBox;
    public javax.swing.JButton topicGo;
    private javax.swing.JLabel topicTxt;
    // End of variables declaration//GEN-END:variables
}
