/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.ComponentOrientation;
import static project.mainScreen.s;

/**
 *
 * @author moizs
 */
public class surahScreen extends javax.swing.JFrame {

    /**
     * Creates new form surahScreen
     */
    public surahScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        surahScreen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        transEng = new javax.swing.JButton();
        transUrdu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Result");
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        surahScreen.setPreferredSize(new java.awt.Dimension(780, 480));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(770, 400));

        display.setEditable(false);
        display.setColumns(20);
        display.setFont(display.getFont().deriveFont(display.getFont().getSize()+10f));
        display.setLineWrap(true);
        display.setRows(5);
        display.setWrapStyleWord(true);
        display.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(display);

        transEng.setText("English Translation");
        transEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transEngActionPerformed(evt);
            }
        });

        transUrdu.setText("Urdu Translation");
        transUrdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transUrduActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout surahScreenLayout = new javax.swing.GroupLayout(surahScreen);
        surahScreen.setLayout(surahScreenLayout);
        surahScreenLayout.setHorizontalGroup(
            surahScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(surahScreenLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(transEng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transUrdu)
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, surahScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        surahScreenLayout.setVerticalGroup(
            surahScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(surahScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(surahScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transEng)
                    .addComponent(transUrdu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(surahScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(surahScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void transEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transEngActionPerformed
        String print;
        if (mainScreen.S == true) {
            int index = mainScreen.surahCBox.getSelectedIndex();
            print = mainScreen.q.getSurahEng(index + 1);
            display.removeAll();
            display.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
            display.setText(print);
            display.setCaretPosition(0);
        }else {
            int indexSurah = mainScreen.surahAyahCBox.getSelectedIndex();
            int indexAyah = mainScreen.ayahCBox.getSelectedIndex();
            print = mainScreen.q.getAyahEnglish(indexSurah + 1, indexAyah + 1);
            display.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
            display.setText(print);
            display.setCaretPosition(0);
        }
    }//GEN-LAST:event_transEngActionPerformed

    private void transUrduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transUrduActionPerformed
        String print;
        if (mainScreen.S == true) {
            int index = mainScreen.surahCBox.getSelectedIndex();
            print = mainScreen.q.getSurahUrdu(index + 1);
            display.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
            display.setText(print);
            display.setCaretPosition(0);
        } else {
            int indexSurah = mainScreen.surahAyahCBox.getSelectedIndex();
            int indexAyah = mainScreen.ayahCBox.getSelectedIndex();
            print = mainScreen.q.getAyahUrdu(indexSurah + 1, indexAyah + 1);
            display.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
            display.setText(print);
            display.setCaretPosition(0);
        }
    }//GEN-LAST:event_transUrduActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(surahScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(surahScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(surahScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(surahScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new surahScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea display;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel surahScreen;
    public javax.swing.JButton transEng;
    public javax.swing.JButton transUrdu;
    // End of variables declaration//GEN-END:variables
}
